# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs

$:.unshift File.dirname(__FILE__)

default_platform :ios


platform :ios do
  before_all do
     # Set project for commit_version_bump, which seems to get confused by projects in other folders
     ENV['FL_BUILD_NUMBER_PROJECT'] = "Wikipedia.xcodeproj"
     ensure_git_status_clean if ENV['FL_ENSURE_CLEAN']
  end

  desc "Upload app store metadata"
  lane :upload_app_store_metadata do
    deliver(skip_binary_upload: true, skip_screenshots: true)
  end

  desc 'Generate App Icon'
  lane :generate_appicon do
    appicon(
      appicon_image_file: 'Icon/wiki-unblocked.png',
      appicon_devices: [:iphone, :ipad, :ios_marketing],
      appicon_path: 'Wikipedia/Images.xcassets',
    )
  end

  desc 'Generate iMessage App Icon'
  lane :generate_imessage do
    appicon(
      appicon_image_file: 'Icon/wiki-unblocked.png',
      appicon_devices: [:iphone, :ipad, :ios_marketing, :messages],
      appicon_path: 'Wikipedia Stickers/Stickers.xcassets',
      appicon_name: 'iMessage App Icon.stickersiconset',
      messages_extension: true
    )
  end

end
